name: 'wgetpaste test runner'
on: [push]
jobs:
  run-test:
    name: 'Run test/test.sh'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: test/test.sh
        shell: bash
  run-test-ansi:
    name: 'Run test/test_ansi.sh'
    # 22.04 is the earliest version that has ansifilter in the repos
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: 'Install ansifilter'
        run: |
          sudo apt-get update
          sudo apt-get install ansifilter
      - run: test/test_ansi.sh
        shell: bash
