name: 'wgetpaste test runner'
on: [pull_request, push]
jobs:
  run-test:
    name: 'Run test/test.sh'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: test/test.sh
        shell: bash
  run-test-ansi:
    name: 'Run test/test_ansi.sh'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Install ansifilter'
        run: |
          sudo apt-get update
          sudo apt-get install ansifilter
      - run: test/test_ansi.sh
        shell: bash
